name: Infra Mais Todos

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: Install AWS CLI v2
      #   run: | 
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip -q awscliv2.zip
      #     sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: cd infra/ && terraform init

      - name: Terraform Format
        run: cd infra/ && terraform fmt # -check

      - name: Terraform Plan
        run: cd infra/ && terraform plan -out=plan.out -input=false -lock-timeout=120s
        # continue-on-error: true

      - name: Terraform Show Plan
        id: tf_show
        run: cd infra/ && terraform show plan.out

      - name: Terraform Apply
        run: cd infra/ && terraform apply -auto-approve -input=false -lock-timeout=120s plan.out

      # - name: Verificar arquivo
      #   run: cd infra/ && cat ec2-key-pair.pem

# # ---

#       # Generates an execution plan for Terraform
#       - name: Terraform Plan
#         run: cd infra/ && terraform plan -out=plan.out -input=false -lock-timeout=120s -destroy
#         # continue-on-error: true

#       - name: Terraform Show Plan
#         id: tf_show
#         run: cd infra/ && terraform show plan.out

#       - name: Terraform Apply
#         # if: github.ref == 'refs/heads/"labs"' && github.event_name == 'push'
#         run: cd infra/ && terraform apply -auto-approve -input=false -lock-timeout=120s plan.out

  selfhosted_job:
    runs-on: self-hosted

    steps:
      - name: Instalação de K3S no Master-1
        run: ssh k3s-master-1 'sudo curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik" sudo sh -'

      - name: Configuração de K3S no Master-1
        run: |
            ssh k3s-master-1 'if [ -d .kube ]; then echo "O diretório já existe, não é necessário criar." else mkdir .kube fi && sudo mv /etc/rancher/k3s/k3s.yaml .kube/config && sudo chmod 0755 .kube/config'
            ssh k3s-master-1 'kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/tigera-operator.yaml && kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/custom-resources.yaml'
            



# # Verifica se o diretório existe
# if [ -d "/caminho/do/seu/diretorio" ]; then
#     echo "O diretório já existe, não é necessário criar."
# else
#     # Se o diretório não existe, então cria
#     mkdir "/caminho/do/seu/diretorio"
#     echo "Diretório criado com sucesso!"
# fi