name: Infra Mais Todos

on:
  push:
    branches:
      - main

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Change to Terraform directory
        run: ls -lha

      - name: Terraform Init
        run: terraform init

# cd /home/runner/work/maistodos/maistodos